version: '3'
services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: 'rabbitmqcontainer'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 8050:15672
      - 5672:5672
    expose:
      - 5672
    networks:
      - fitnetwork
 
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=FITCCRs2App123!
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    networks:
      - fitnetwork
 
  rabbitmq-service:
    build:
      context: .
      dockerfile: RabbitMQConsumer\Dockerfile
    environment:
      RABBITMQ_HOST: "rabbitMQ"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USERNAME: "guest"
      RABBITMQ_PASSWORD: "guest"
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USERNAME: "mellimostar@gmail.com"
      SMTP_PASSWORD: "ttydocdytcokyeru"
      API_HOST: "localhost"
      API_PORT: "7247"
    depends_on:
      - rabbitMQ
      - sql
    networks:
      - fitnetwork
 
  fitccrs2app-api:
    build:
      context: .
      dockerfile: FITCCApp\Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=sql,1433;Database=RS190039;User=sa;Password=FITCCRs2App123!;TrustServerCertificate=True;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx
      - IdentityServerUrl=https://fitccrs2app-identityserver
      - IdentityServerMetaDataUrl=http://fitccrs2app-identityserver/.well-known/openid-configuration
      - JWTSecret=ee7891bac2a8e9493b204d6bcc850194
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=mellimostar@gmail.com
      - SMTP_PASSWORD=ttydocdytcokyeru
    ports:
      - 7247:7247
    networks:
      - fitnetwork
    depends_on:
      - sql
      - rabbitMQ
 
  identityserver:
    restart: unless-stopped
    build:
      context: .
      dockerfile: FITCCRS2App.IdentityServer\Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=sql,1433;Database=RS190039;User=sa;Password=FITCCRs2App123!;TrustServerCertificate=True;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=44301
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx
      - JWTSecret=ee7891bac2a8e9493b204d6bcc850194
    ports:
      - 5443:5443
    networks:
      - fitnetwork
    depends_on:
      - sql
 
 
   
     
networks:
  fitnetwork:
    driver: bridge
