version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmqcontainer'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 8050:15672
      - 5672:5672
    expose:
      - 5672
    networks:
      - fitnetwork
 
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass123!!
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    networks:
      - fitnetwork
 
  rabbitmq-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: RabbitMQConsumer/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=mellimostar@gmail.com
      - SMTP_PASSWORD=ttydocdytcokyeru
      - API_HOST=localhost
      - API_PORT=7247
    depends_on:
      - rabbitmq
      - fitccrs2app-api
      - sql
    networks:
      - fitnetwork
      
  fitccrs2app-api:
    build:
      context: .
      dockerfile: FITCCApp/Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=sql,1433;Database=RS190039;User=sa;Password=Pass123!!;TrustServerCertificate=True;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+;http://+
      # - ASPNETCORE_HTTPS_PORT=7247
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx
      # - IdentityServerUrl=https://identityserver
      # - IdentityServerMetaDataUrl=http://identityserver/.well-known/openid-configuration
      - JWTSecret=ee7891bac2a8e9493b204d6bcc850194
      - ConnectionStrings:IdentityAuthority=http://identityserver:5001
      - Issuer=http://identityserver:5001
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=mellimostar@gmail.com
      - SMTP_PASSWORD=ttydocdytcokyeru
      # - API_HOST=localhost
      # - API_PORT=7247
    ports:
      - 7247:80
      - 7248:443
    networks:
      - fitnetwork
    depends_on:
      - sql
      - rabbitmq
      - identityserver
 
  identityserver:
    restart: unless-stopped
    build:
      context: .
      dockerfile: FITCCRS2App.IdentityServer/Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=sql,1433;Database=RS190039;User=sa;Password=Pass123!!;TrustServerCertificate=True;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+;http://+
      # - ASPNETCORE_HTTPS_PORT=51443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx
      - JWTSecret=ee7891bac2a8e9493b204d6bcc850194
    ports:
     - 5001:80
    networks:
      - fitnetwork
    depends_on:
      - sql
 
 
   
     
networks:
  fitnetwork:
    driver: bridge
