version: '3'
services:
  rabbitMQ:
    container_name: 'rabbitmq_container'
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 8050:15672
      - 5672:5672
    expose:
      - 5672
    networks: 
      - fitccnetwork

  sql:
    container_name: 'sql'
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=FITCCRs2App123!
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    networks:
      - fitccnetwork
      
  rabbitmq-service:
    build:
      context: .
      dockerfile: ./FITCCRS2App/FITCCRS2App.RabbitMQConsumer/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=mellimostar@gmail.com
      - SMTP_PASSWORD=ttydocdytcokyeru
      - API_HOST=localhost
      - API_PORT=7247
    depends_on:
      - rabbitMQ
      - sql
      - fitccrs2app-api
    networks:
      - fitccnetwork

  identityserver:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./FITCCRS2App/FITCCRS2App.IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=44301
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=certificate.pfx
      - ConnectionStrings__fitccrs2app_Database=Server=sql,1433;Database=RS190039;Trusted_Connection=False;Encrypt=False;User=SA;Password=FITCCRs2App123!
      - JWTSecret=ee7891bac2a8e9493b204d6bcc850194
    ports:
      - 5001:5000
    networks:
      - fitccnetwork
    depends_on:
      - sql

  fitccrs2app-api:
    build:
      context: .
      dockerfile: ./FITCCRS2App/FITCCApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7247
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=certificate.pfx
      - ConnectionStrings__fitccrs2app_Database=Server=sql,1433;Trusted_Connection=False;Encrypt=False;Database=RS190039;User=SA;Password=FITCCRs2App123!
      - IdentityServerUrl=https://identityserver
      - IdentityServerMetaDataUrl=http://identityserver/.well-known/openid-configuration
      - JWTSecret=ee7891bac2a8e9493b204d6bcc850194
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=mellimostar@gmail.com
      - SMTP_PASSWORD=ttydocdytcokyeru
      - API_HOST=localhost
      - API_PORT=7247
    ports:
      - "7247:7247"
    depends_on:
      - sql
      - rabbitMQ
      - identityserver
      - rabbitmq-service
    networks:
      - fitccnetwork
      
networks:
  fitccnetwork:
    driver: bridge
